### ISSUE TITLE
Implement Task History Tracking

### ISSUE THREAD

**Issue by Oranged9922** [Oranged9922/TaskManager#16]
Implement a mechanism to track the history of tasks, including changes, updates, creations, and state changes.

## Steps
1. Create a `TaskHistory` model to store task history events.
2. Add a corresponding `DbSet<TaskHistory>` in the DbContext.
3. Run Entity Framework migrations to create the `TaskHistories` table in SQLite.
4. Implement event handlers or triggers to capture task events and populate the `TaskHistories` table.
5. Update API endpoints to return task history when requested.
6. Update README with task history tracking instructions.

## Code Hint
For SQLite, your `TaskHistory` model and `DbContext` might look like:
```csharp
// TaskHistory Model
public class TaskHistory
{
    public int Id { get; set; }
    public int TaskId { get; set; }
    public string EventType { get; set; }
    public string Details { get; set; }
    public DateTime Timestamp { get; set; }
}

// In DbContext
public DbSet<TaskHistory> TaskHistories { get; set; }
```
Run EF migrations to create the table:
```bash
dotnet ef migrations add CreateTaskHistoryTable
dotnet ef database update
```

## Acceptance Criteria
- [ ] `TaskHistories` table created in SQLite database.
- [ ] Task events are captured and stored in `TaskHistories`.
- [ ] API endpoints updated to return task history.
- [ ] README updated with task history tracking instructions.
```

Difficulty: Moderate to High, involves database schema changes, event handling, and API updates.
